### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by commitqdy** [myadmin/music#1]
为什么你这样做，获取到的音乐就可以播放。我用jsonp调接口，获取到的播放地址可以下载，但是不能播放，报403的错误。求大神告知

**Comment by myadmin** [comment]
@commitqdy 我用的是后端转发了一次请求，因为后端发请求是没有跨域限制的。
你用的是什么音乐接口？

**Comment by commitqdy** [comment]
我用的也是百度音乐的接口，没有用后台转发。用jsonp做的，其他接口都可以调用，就是获取到的音乐地址播放会报403的错，可能是百度对这种方式获取的下载地址做了限制。

**Comment by myadmin** [comment]
@commitqdy 关于使用file_link不能播放的问题，是因为百度使用Http中的Referer头字段来防止盗链，在HTML文件中加上 &lt;meta name="referrer" content="never"&gt;这一句让发送出去的Http包都不含Referer字段就行了

**Comment by myadmin** [comment]
meta name="referrer" content="never"

**Comment by commitqdy** [comment]
大神，多谢多谢，这个问题纠结了我一个月了，感谢感谢
