### ISSUE TITLE
域名到期问题

### ISSUE THREAD

**Issue by soldier7815** [myadmin/music#3]
嘿！老哥觉得你的软件做的挺实用的，可以下一些网易vip的歌，但域名快到期了，感觉有点可惜，有续费的打算嘛，或者募捐续费？

**Comment by myadmin** [comment]
@soldier7815 你可以自己在本地部署这个项目[Music Api](https://binaryify.github.io/NeteaseCloudMusicApi)，然后也一样可以运行，或者把我的这个项目拉取到本地，也是可以正常运行的。
